/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.ApplicationResponse = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ApplicationResponse model module.
   * @module model/ApplicationResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ApplicationResponse</code>.
   * @alias module:model/ApplicationResponse
   * @class
   * @param uidLeader {String} 
   */
  var exports = function(uidLeader) {
    var _this = this;




    _this['uid_leader'] = uidLeader;












  };

  /**
   * Constructs a <code>ApplicationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplicationResponse} obj Optional instance to populate.
   * @return {module:model/ApplicationResponse} The populated <code>ApplicationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('summary')) {
        obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
      }
      if (data.hasOwnProperty('uid_leader')) {
        obj['uid_leader'] = ApiClient.convertToType(data['uid_leader'], 'String');
      }
      if (data.hasOwnProperty('leader_name')) {
        obj['leader_name'] = ApiClient.convertToType(data['leader_name'], 'String');
      }
      if (data.hasOwnProperty('leader_summary')) {
        obj['leader_summary'] = ApiClient.convertToType(data['leader_summary'], 'String');
      }
      if (data.hasOwnProperty('leader_phone')) {
        obj['leader_phone'] = ApiClient.convertToType(data['leader_phone'], 'String');
      }
      if (data.hasOwnProperty('leader_weixin')) {
        obj['leader_weixin'] = ApiClient.convertToType(data['leader_weixin'], 'String');
      }
      if (data.hasOwnProperty('other_info')) {
        obj['other_info'] = ApiClient.convertToType(data['other_info'], 'String');
      }
      if (data.hasOwnProperty('realm')) {
        obj['realm'] = ApiClient.convertToType(data['realm'], 'String');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ApiClient.convertToType(data['image'], 'String');
      }
      if (data.hasOwnProperty('welcome')) {
        obj['welcome'] = ApiClient.convertToType(data['welcome'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('reason')) {
        obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   * @default ''
   */
  exports.prototype['name'] = '';
  /**
   * @member {String} summary
   * @default ''
   */
  exports.prototype['summary'] = '';
  /**
   * @member {String} uid_leader
   */
  exports.prototype['uid_leader'] = undefined;
  /**
   * @member {String} leader_name
   * @default ''
   */
  exports.prototype['leader_name'] = '';
  /**
   * @member {String} leader_summary
   * @default ''
   */
  exports.prototype['leader_summary'] = '';
  /**
   * @member {String} leader_phone
   * @default ''
   */
  exports.prototype['leader_phone'] = '';
  /**
   * @member {String} leader_weixin
   * @default ''
   */
  exports.prototype['leader_weixin'] = '';
  /**
   * @member {String} other_info
   * @default ''
   */
  exports.prototype['other_info'] = '';
  /**
   * @member {String} realm
   * @default ''
   */
  exports.prototype['realm'] = '';
  /**
   * @member {String} image
   */
  exports.prototype['image'] = undefined;
  /**
   * @member {String} welcome
   */
  exports.prototype['welcome'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {module:model/ApplicationResponse.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} reason
   * @default ''
   */
  exports.prototype['reason'] = '';
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",
    /**
     * value: "passed"
     * @const
     */
    "passed": "passed",
    /**
     * value: "refused"
     * @const
     */
    "refused": "refused",
    /**
     * value: "cancelled"
     * @const
     */
    "cancelled": "cancelled"  };


  return exports;
}));


