/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MemberResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MemberResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.AuthorMember = factory(root.Mimir.ApiClient, root.Mimir.MemberResponse);
  }
}(this, function(ApiClient, MemberResponse) {
  'use strict';




  /**
   * The AuthorMember model module.
   * @module model/AuthorMember
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AuthorMember</code>.
   * @alias module:model/AuthorMember
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>AuthorMember</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthorMember} obj Optional instance to populate.
   * @return {module:model/AuthorMember} The populated <code>AuthorMember</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('author_member')) {
        obj['author_member'] = MemberResponse.constructFromObject(data['author_member']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/MemberResponse} author_member
   */
  exports.prototype['author_member'] = undefined;



  return exports;
}));


