/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthorItem', 'model/AwardItem', 'model/BasicShare', 'model/RichShareContent', 'model/SimpleUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AuthorItem'), require('./AwardItem'), require('./BasicShare'), require('./RichShareContent'), require('./SimpleUser'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.AwardResponse = factory(root.Mimir.ApiClient, root.Mimir.AuthorItem, root.Mimir.AwardItem, root.Mimir.BasicShare, root.Mimir.RichShareContent, root.Mimir.SimpleUser);
  }
}(this, function(ApiClient, AuthorItem, AwardItem, BasicShare, RichShareContent, SimpleUser) {
  'use strict';




  /**
   * The AwardResponse model module.
   * @module model/AwardResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AwardResponse</code>.
   * @alias module:model/AwardResponse
   * @class
   * @extends module:model/BasicShare
   * @implements module:model/AuthorItem
   * @implements module:model/AwardItem
   */
  var exports = function() {
    var _this = this;
    BasicShare.call(_this);
    AuthorItem.call(_this);
    AwardItem.call(_this);

  };

  /**
   * Constructs a <code>AwardResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AwardResponse} obj Optional instance to populate.
   * @return {module:model/AwardResponse} The populated <code>AwardResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      BasicShare.constructFromObject(data, obj);
      AuthorItem.constructFromObject(data, obj);
      AwardItem.constructFromObject(data, obj);
      if (data.hasOwnProperty('recommended_by')) {
        obj['recommended_by'] = ApiClient.convertToType(data['recommended_by'], 'String');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(BasicShare.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {String} recommended_by
   */
  exports.prototype['recommended_by'] = undefined;

  // Implement AuthorItem interface:
  /**
   * @member {module:model/SimpleUser} author
   */
exports.prototype['author'] = undefined;

  // Implement AwardItem interface:
  /**
   * @member {Number} award
   */
exports.prototype['award'] = undefined;



  return exports;
}));


