/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.CachedReplyResponse = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CachedReplyResponse model module.
   * @module model/CachedReplyResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CachedReplyResponse</code>.
   * @alias module:model/CachedReplyResponse
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>CachedReplyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CachedReplyResponse} obj Optional instance to populate.
   * @return {module:model/CachedReplyResponse} The populated <code>CachedReplyResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('author')) {
        obj['author'] = ApiClient.convertToType(data['author'], 'String');
      }
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('author_ranking')) {
        obj['author_ranking'] = ApiClient.convertToType(data['author_ranking'], 'String');
      }
      if (data.hasOwnProperty('quote_author')) {
        obj['quote_author'] = ApiClient.convertToType(data['quote_author'], 'String');
      }
      if (data.hasOwnProperty('quote_author_ranking')) {
        obj['quote_author_ranking'] = ApiClient.convertToType(data['quote_author_ranking'], 'String');
      }
      if (data.hasOwnProperty('is_author_great')) {
        obj['is_author_great'] = ApiClient.convertToType(data['is_author_great'], 'Boolean');
      }
      if (data.hasOwnProperty('is_quote_author_great')) {
        obj['is_quote_author_great'] = ApiClient.convertToType(data['is_quote_author_great'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} author
   */
  exports.prototype['author'] = undefined;
  /**
   * @member {String} text
   */
  exports.prototype['text'] = undefined;
  /**
   * @member {String} author_ranking
   */
  exports.prototype['author_ranking'] = undefined;
  /**
   * @member {String} quote_author
   */
  exports.prototype['quote_author'] = undefined;
  /**
   * @member {String} quote_author_ranking
   */
  exports.prototype['quote_author_ranking'] = undefined;
  /**
   * @member {Boolean} is_author_great
   */
  exports.prototype['is_author_great'] = undefined;
  /**
   * @member {Boolean} is_quote_author_great
   */
  exports.prototype['is_quote_author_great'] = undefined;



  return exports;
}));


