/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CachedAwardResponse', 'model/CachedReplyResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CachedAwardResponse'), require('./CachedReplyResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.CachedShareExtraData = factory(root.Mimir.ApiClient, root.Mimir.CachedAwardResponse, root.Mimir.CachedReplyResponse);
  }
}(this, function(ApiClient, CachedAwardResponse, CachedReplyResponse) {
  'use strict';




  /**
   * The CachedShareExtraData model module.
   * @module model/CachedShareExtraData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CachedShareExtraData</code>.
   * @alias module:model/CachedShareExtraData
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>CachedShareExtraData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CachedShareExtraData} obj Optional instance to populate.
   * @return {module:model/CachedShareExtraData} The populated <code>CachedShareExtraData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('awards')) {
        obj['awards'] = ApiClient.convertToType(data['awards'], [CachedAwardResponse]);
      }
      if (data.hasOwnProperty('replies')) {
        obj['replies'] = ApiClient.convertToType(data['replies'], [CachedReplyResponse]);
      }
      if (data.hasOwnProperty('recommends')) {
        obj['recommends'] = ApiClient.convertToType(data['recommends'], [CachedReplyResponse]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/CachedAwardResponse>} awards
   */
  exports.prototype['awards'] = undefined;
  /**
   * @member {Array.<module:model/CachedReplyResponse>} replies
   */
  exports.prototype['replies'] = undefined;
  /**
   * @member {Array.<module:model/CachedReplyResponse>} recommends
   */
  exports.prototype['recommends'] = undefined;



  return exports;
}));


