/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.FavoriteRequest = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FavoriteRequest model module.
   * @module model/FavoriteRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FavoriteRequest</code>.
   * @alias module:model/FavoriteRequest
   * @class
   * @param shareId {Number} 
   */
  var exports = function(shareId) {
    var _this = this;

    _this['share_id'] = shareId;
  };

  /**
   * Constructs a <code>FavoriteRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FavoriteRequest} obj Optional instance to populate.
   * @return {module:model/FavoriteRequest} The populated <code>FavoriteRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('share_id')) {
        obj['share_id'] = ApiClient.convertToType(data['share_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} share_id
   */
  exports.prototype['share_id'] = undefined;



  return exports;
}));


