/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GroupShareItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GroupShareItem'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.FavoriteItem = factory(root.Mimir.ApiClient, root.Mimir.GroupShareItem);
  }
}(this, function(ApiClient, GroupShareItem) {
  'use strict';




  /**
   * The FavoriteItem model module.
   * @module model/FavoriteItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FavoriteItem</code>.
   * @alias module:model/FavoriteItem
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>FavoriteItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FavoriteItem} obj Optional instance to populate.
   * @return {module:model/FavoriteItem} The populated <code>FavoriteItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('share_id')) {
        obj['share_id'] = ApiClient.convertToType(data['share_id'], 'Number');
      }
      if (data.hasOwnProperty('topic')) {
        obj['topic'] = GroupShareItem.constructFromObject(data['topic']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Number} share_id
   */
  exports.prototype['share_id'] = undefined;
  /**
   * @member {module:model/GroupShareItem} topic
   */
  exports.prototype['topic'] = undefined;



  return exports;
}));


