/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BasicShare', 'model/CategoryResponse', 'model/GroupExtraData', 'model/GroupInvitations', 'model/GroupPrivilege', 'model/GroupStatistics', 'model/InvitationResponse', 'model/MemberUserResponse', 'model/SimpleGroup', 'model/SimpleUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BasicShare'), require('./CategoryResponse'), require('./GroupExtraData'), require('./GroupInvitations'), require('./GroupPrivilege'), require('./GroupStatistics'), require('./InvitationResponse'), require('./MemberUserResponse'), require('./SimpleGroup'), require('./SimpleUser'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.GroupResponse = factory(root.Mimir.ApiClient, root.Mimir.BasicShare, root.Mimir.CategoryResponse, root.Mimir.GroupExtraData, root.Mimir.GroupInvitations, root.Mimir.GroupPrivilege, root.Mimir.GroupStatistics, root.Mimir.InvitationResponse, root.Mimir.MemberUserResponse, root.Mimir.SimpleGroup, root.Mimir.SimpleUser);
  }
}(this, function(ApiClient, BasicShare, CategoryResponse, GroupExtraData, GroupInvitations, GroupPrivilege, GroupStatistics, InvitationResponse, MemberUserResponse, SimpleGroup, SimpleUser) {
  'use strict';




  /**
   * The GroupResponse model module.
   * @module model/GroupResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupResponse</code>.
   * @alias module:model/GroupResponse
   * @class
   * @extends module:model/SimpleGroup
   * @implements module:model/GroupExtraData
   * @implements module:model/GroupInvitations
   * @implements module:model/GroupPrivilege
   */
  var exports = function() {
    var _this = this;
    SimpleGroup.call(_this);
    GroupExtraData.call(_this);
    GroupInvitations.call(_this);
    GroupPrivilege.call(_this);

  };

  /**
   * Constructs a <code>GroupResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupResponse} obj Optional instance to populate.
   * @return {module:model/GroupResponse} The populated <code>GroupResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      SimpleGroup.constructFromObject(data, obj);
      GroupExtraData.constructFromObject(data, obj);
      GroupInvitations.constructFromObject(data, obj);
      GroupPrivilege.constructFromObject(data, obj);
      if (data.hasOwnProperty('cur_member_end_at')) {
        obj['cur_member_end_at'] = ApiClient.convertToType(data['cur_member_end_at'], 'String');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(SimpleGroup.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {String} cur_member_end_at
   */
  exports.prototype['cur_member_end_at'] = undefined;

  // Implement GroupExtraData interface:
  /**
   * @member {Number} application_id
   */
exports.prototype['application_id'] = undefined;

  /**
   * @member {String} invite_code
   */
exports.prototype['invite_code'] = undefined;

  /**
   * @member {String} name
   * @default ''
   */
exports.prototype['name'] = '';

  /**
   * @member {String} image
   * @default ''
   */
exports.prototype['image'] = '';

  /**
   * @member {String} image_url
   */
exports.prototype['image_url'] = undefined;

  /**
   * @member {String} summary
   * @default ''
   */
exports.prototype['summary'] = '';

  /**
   * @member {String} welcome
   * @default ''
   */
exports.prototype['welcome'] = '';

  /**
   * @member {module:model/SimpleUser} leader
   */
exports.prototype['leader'] = undefined;

  /**
   * @member {String} leader_name
   * @default ''
   */
exports.prototype['leader_name'] = '';

  /**
   * @member {String} leader_summary
   * @default ''
   */
exports.prototype['leader_summary'] = '';

  /**
   * @member {String} leader_phone
   * @default ''
   */
exports.prototype['leader_phone'] = '';

  /**
   * @member {String} leader_weixin
   * @default ''
   */
exports.prototype['leader_weixin'] = '';

  /**
   * @member {String} realm
   * @default ''
   */
exports.prototype['realm'] = '';

  /**
   * @member {Number} price
   */
exports.prototype['price'] = undefined;

  /**
   * @member {Number} funs_count
   */
exports.prototype['funs_count'] = undefined;

  /**
   * @member {Number} unread_share_count
   */
exports.prototype['unread_share_count'] = undefined;

  /**
   * @member {Number} unread_reply_count
   */
exports.prototype['unread_reply_count'] = undefined;

  /**
   * @member {Boolean} has_unread_question
   * @default false
   */
exports.prototype['has_unread_question'] = false;

  /**
   * @member {Date} created_at
   */
exports.prototype['created_at'] = undefined;

  /**
   * @member {Boolean} invitation_privileges
   */
exports.prototype['invitation_privileges'] = undefined;

  /**
   * @member {Boolean} current_user_is_effect
   */
exports.prototype['current_user_is_effect'] = undefined;

  /**
   * @member {Number} can_invite_count
   */
exports.prototype['can_invite_count'] = undefined;

  /**
   * @member {Boolean} is_expired
   */
exports.prototype['is_expired'] = undefined;

  /**
   * @member {module:model/BasicShare} last_share
   */
exports.prototype['last_share'] = undefined;

  /**
   * @member {module:model/GroupStatistics} statistics
   */
exports.prototype['statistics'] = undefined;

  /**
   * @member {module:model/CategoryResponse} category
   */
exports.prototype['category'] = undefined;

  /**
   * @member {Array.<module:model/MemberUserResponse>} guests
   */
exports.prototype['guests'] = undefined;

  // Implement GroupInvitations interface:
  /**
   * @member {Array.<module:model/InvitationResponse>} invitations
   */
exports.prototype['invitations'] = undefined;

  // Implement GroupPrivilege interface:
  /**
   * @member {Boolean} cur_user_is_up_guest
   */
exports.prototype['cur_user_is_up_guest'] = undefined;

  /**
   * @member {Boolean} cur_member_is_prisoner
   */
exports.prototype['cur_member_is_prisoner'] = undefined;

  /**
   * @member {Number} cur_user_free_read_left
   */
exports.prototype['cur_user_free_read_left'] = undefined;



  return exports;
}));


