/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.GroupChargeResponse = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GroupChargeResponse model module.
   * @module model/GroupChargeResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupChargeResponse</code>.
   * @alias module:model/GroupChargeResponse
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>GroupChargeResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupChargeResponse} obj Optional instance to populate.
   * @return {module:model/GroupChargeResponse} The populated <code>GroupChargeResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('30')) {
        obj['30'] = ApiClient.convertToType(data['30'], 'Number');
      }
      if (data.hasOwnProperty('90')) {
        obj['90'] = ApiClient.convertToType(data['90'], 'Number');
      }
      if (data.hasOwnProperty('180')) {
        obj['180'] = ApiClient.convertToType(data['180'], 'Number');
      }
      if (data.hasOwnProperty('360')) {
        obj['360'] = ApiClient.convertToType(data['360'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} 30
   */
  exports.prototype['30'] = undefined;
  /**
   * @member {Number} 90
   */
  exports.prototype['90'] = undefined;
  /**
   * @member {Number} 180
   */
  exports.prototype['180'] = undefined;
  /**
   * @member {Number} 360
   */
  exports.prototype['360'] = undefined;



  return exports;
}));


