/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BasicShare', 'model/CategoryResponse', 'model/GroupStatistics', 'model/MemberUserResponse', 'model/SimpleUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BasicShare'), require('./CategoryResponse'), require('./GroupStatistics'), require('./MemberUserResponse'), require('./SimpleUser'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.GroupExtraData = factory(root.Mimir.ApiClient, root.Mimir.BasicShare, root.Mimir.CategoryResponse, root.Mimir.GroupStatistics, root.Mimir.MemberUserResponse, root.Mimir.SimpleUser);
  }
}(this, function(ApiClient, BasicShare, CategoryResponse, GroupStatistics, MemberUserResponse, SimpleUser) {
  'use strict';




  /**
   * The GroupExtraData model module.
   * @module model/GroupExtraData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupExtraData</code>.
   * @alias module:model/GroupExtraData
   * @class
   */
  var exports = function() {
    var _this = this;




























  };

  /**
   * Constructs a <code>GroupExtraData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupExtraData} obj Optional instance to populate.
   * @return {module:model/GroupExtraData} The populated <code>GroupExtraData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('application_id')) {
        obj['application_id'] = ApiClient.convertToType(data['application_id'], 'Number');
      }
      if (data.hasOwnProperty('invite_code')) {
        obj['invite_code'] = ApiClient.convertToType(data['invite_code'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ApiClient.convertToType(data['image'], 'String');
      }
      if (data.hasOwnProperty('image_url')) {
        obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
      }
      if (data.hasOwnProperty('summary')) {
        obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
      }
      if (data.hasOwnProperty('welcome')) {
        obj['welcome'] = ApiClient.convertToType(data['welcome'], 'String');
      }
      if (data.hasOwnProperty('leader')) {
        obj['leader'] = SimpleUser.constructFromObject(data['leader']);
      }
      if (data.hasOwnProperty('leader_name')) {
        obj['leader_name'] = ApiClient.convertToType(data['leader_name'], 'String');
      }
      if (data.hasOwnProperty('leader_summary')) {
        obj['leader_summary'] = ApiClient.convertToType(data['leader_summary'], 'String');
      }
      if (data.hasOwnProperty('leader_phone')) {
        obj['leader_phone'] = ApiClient.convertToType(data['leader_phone'], 'String');
      }
      if (data.hasOwnProperty('leader_weixin')) {
        obj['leader_weixin'] = ApiClient.convertToType(data['leader_weixin'], 'String');
      }
      if (data.hasOwnProperty('realm')) {
        obj['realm'] = ApiClient.convertToType(data['realm'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('funs_count')) {
        obj['funs_count'] = ApiClient.convertToType(data['funs_count'], 'Number');
      }
      if (data.hasOwnProperty('unread_share_count')) {
        obj['unread_share_count'] = ApiClient.convertToType(data['unread_share_count'], 'Number');
      }
      if (data.hasOwnProperty('unread_reply_count')) {
        obj['unread_reply_count'] = ApiClient.convertToType(data['unread_reply_count'], 'Number');
      }
      if (data.hasOwnProperty('has_unread_question')) {
        obj['has_unread_question'] = ApiClient.convertToType(data['has_unread_question'], 'Boolean');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('invitation_privileges')) {
        obj['invitation_privileges'] = ApiClient.convertToType(data['invitation_privileges'], 'Boolean');
      }
      if (data.hasOwnProperty('current_user_is_effect')) {
        obj['current_user_is_effect'] = ApiClient.convertToType(data['current_user_is_effect'], 'Boolean');
      }
      if (data.hasOwnProperty('can_invite_count')) {
        obj['can_invite_count'] = ApiClient.convertToType(data['can_invite_count'], 'Number');
      }
      if (data.hasOwnProperty('is_expired')) {
        obj['is_expired'] = ApiClient.convertToType(data['is_expired'], 'Boolean');
      }
      if (data.hasOwnProperty('last_share')) {
        obj['last_share'] = BasicShare.constructFromObject(data['last_share']);
      }
      if (data.hasOwnProperty('statistics')) {
        obj['statistics'] = GroupStatistics.constructFromObject(data['statistics']);
      }
      if (data.hasOwnProperty('category')) {
        obj['category'] = CategoryResponse.constructFromObject(data['category']);
      }
      if (data.hasOwnProperty('guests')) {
        obj['guests'] = ApiClient.convertToType(data['guests'], [MemberUserResponse]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} application_id
   */
  exports.prototype['application_id'] = undefined;
  /**
   * @member {String} invite_code
   */
  exports.prototype['invite_code'] = undefined;
  /**
   * @member {String} name
   * @default ''
   */
  exports.prototype['name'] = '';
  /**
   * @member {String} image
   * @default ''
   */
  exports.prototype['image'] = '';
  /**
   * @member {String} image_url
   */
  exports.prototype['image_url'] = undefined;
  /**
   * @member {String} summary
   * @default ''
   */
  exports.prototype['summary'] = '';
  /**
   * @member {String} welcome
   * @default ''
   */
  exports.prototype['welcome'] = '';
  /**
   * @member {module:model/SimpleUser} leader
   */
  exports.prototype['leader'] = undefined;
  /**
   * @member {String} leader_name
   * @default ''
   */
  exports.prototype['leader_name'] = '';
  /**
   * @member {String} leader_summary
   * @default ''
   */
  exports.prototype['leader_summary'] = '';
  /**
   * @member {String} leader_phone
   * @default ''
   */
  exports.prototype['leader_phone'] = '';
  /**
   * @member {String} leader_weixin
   * @default ''
   */
  exports.prototype['leader_weixin'] = '';
  /**
   * @member {String} realm
   * @default ''
   */
  exports.prototype['realm'] = '';
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {Number} funs_count
   */
  exports.prototype['funs_count'] = undefined;
  /**
   * @member {Number} unread_share_count
   */
  exports.prototype['unread_share_count'] = undefined;
  /**
   * @member {Number} unread_reply_count
   */
  exports.prototype['unread_reply_count'] = undefined;
  /**
   * @member {Boolean} has_unread_question
   * @default false
   */
  exports.prototype['has_unread_question'] = false;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Boolean} invitation_privileges
   */
  exports.prototype['invitation_privileges'] = undefined;
  /**
   * @member {Boolean} current_user_is_effect
   */
  exports.prototype['current_user_is_effect'] = undefined;
  /**
   * @member {Number} can_invite_count
   */
  exports.prototype['can_invite_count'] = undefined;
  /**
   * @member {Boolean} is_expired
   */
  exports.prototype['is_expired'] = undefined;
  /**
   * @member {module:model/BasicShare} last_share
   */
  exports.prototype['last_share'] = undefined;
  /**
   * @member {module:model/GroupStatistics} statistics
   */
  exports.prototype['statistics'] = undefined;
  /**
   * @member {module:model/CategoryResponse} category
   */
  exports.prototype['category'] = undefined;
  /**
   * @member {Array.<module:model/MemberUserResponse>} guests
   */
  exports.prototype['guests'] = undefined;



  return exports;
}));


