/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PrivilegeGroup', 'model/QuestionResponse', 'model/RichShareContent', 'model/ShareRepItem', 'model/SimpleUser', 'model/TagResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PrivilegeGroup'), require('./QuestionResponse'), require('./RichShareContent'), require('./ShareRepItem'), require('./SimpleUser'), require('./TagResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.GroupShareRepItem = factory(root.Mimir.ApiClient, root.Mimir.PrivilegeGroup, root.Mimir.QuestionResponse, root.Mimir.RichShareContent, root.Mimir.ShareRepItem, root.Mimir.SimpleUser, root.Mimir.TagResponse);
  }
}(this, function(ApiClient, PrivilegeGroup, QuestionResponse, RichShareContent, ShareRepItem, SimpleUser, TagResponse) {
  'use strict';




  /**
   * The GroupShareRepItem model module.
   * @module model/GroupShareRepItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupShareRepItem</code>.
   * @alias module:model/GroupShareRepItem
   * @class
   * @extends module:model/ShareRepItem
   */
  var exports = function() {
    var _this = this;
    ShareRepItem.call(_this);

  };

  /**
   * Constructs a <code>GroupShareRepItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupShareRepItem} obj Optional instance to populate.
   * @return {module:model/GroupShareRepItem} The populated <code>GroupShareRepItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ShareRepItem.constructFromObject(data, obj);
      if (data.hasOwnProperty('group')) {
        obj['group'] = PrivilegeGroup.constructFromObject(data['group']);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(ShareRepItem.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/PrivilegeGroup} group
   */
  exports.prototype['group'] = undefined;



  return exports;
}));


