/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BasicShare', 'model/CategoryResponse', 'model/GroupResponse', 'model/GroupStatistics', 'model/InvitationResponse', 'model/MemberUserResponse', 'model/SimpleUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BasicShare'), require('./CategoryResponse'), require('./GroupResponse'), require('./GroupStatistics'), require('./InvitationResponse'), require('./MemberUserResponse'), require('./SimpleUser'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.GroupResponseCanEmpty = factory(root.Mimir.ApiClient, root.Mimir.BasicShare, root.Mimir.CategoryResponse, root.Mimir.GroupResponse, root.Mimir.GroupStatistics, root.Mimir.InvitationResponse, root.Mimir.MemberUserResponse, root.Mimir.SimpleUser);
  }
}(this, function(ApiClient, BasicShare, CategoryResponse, GroupResponse, GroupStatistics, InvitationResponse, MemberUserResponse, SimpleUser) {
  'use strict';




  /**
   * The GroupResponseCanEmpty model module.
   * @module model/GroupResponseCanEmpty
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupResponseCanEmpty</code>.
   * @alias module:model/GroupResponseCanEmpty
   * @class
   * @extends module:model/GroupResponse
   */
  var exports = function() {
    var _this = this;
    GroupResponse.call(_this);

  };

  /**
   * Constructs a <code>GroupResponseCanEmpty</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupResponseCanEmpty} obj Optional instance to populate.
   * @return {module:model/GroupResponseCanEmpty} The populated <code>GroupResponseCanEmpty</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      GroupResponse.constructFromObject(data, obj);
      if (data.hasOwnProperty('invitations')) {
        obj['invitations'] = ApiClient.convertToType(data['invitations'], [InvitationResponse]);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(GroupResponse.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Array.<module:model/InvitationResponse>} invitations
   */
  exports.prototype['invitations'] = undefined;



  return exports;
}));


