/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.GroupStatistics = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GroupStatistics model module.
   * @module model/GroupStatistics
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupStatistics</code>.
   * @alias module:model/GroupStatistics
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>GroupStatistics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupStatistics} obj Optional instance to populate.
   * @return {module:model/GroupStatistics} The populated <code>GroupStatistics</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('share_count')) {
        obj['share_count'] = ApiClient.convertToType(data['share_count'], 'Number');
      }
      if (data.hasOwnProperty('reply_count')) {
        obj['reply_count'] = ApiClient.convertToType(data['reply_count'], 'Number');
      }
      if (data.hasOwnProperty('member_count')) {
        obj['member_count'] = ApiClient.convertToType(data['member_count'], 'Number');
      }
      if (data.hasOwnProperty('income')) {
        obj['income'] = ApiClient.convertToType(data['income'], 'Number');
      }
      if (data.hasOwnProperty('leader_money')) {
        obj['leader_money'] = ApiClient.convertToType(data['leader_money'], 'Number');
      }
      if (data.hasOwnProperty('money')) {
        obj['money'] = ApiClient.convertToType(data['money'], 'Number');
      }
      if (data.hasOwnProperty('question_count')) {
        obj['question_count'] = ApiClient.convertToType(data['question_count'], 'Number');
      }
      if (data.hasOwnProperty('unanswered_question_count')) {
        obj['unanswered_question_count'] = ApiClient.convertToType(data['unanswered_question_count'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} share_count
   */
  exports.prototype['share_count'] = undefined;
  /**
   * @member {Number} reply_count
   */
  exports.prototype['reply_count'] = undefined;
  /**
   * @member {Number} member_count
   */
  exports.prototype['member_count'] = undefined;
  /**
   * @member {Number} income
   */
  exports.prototype['income'] = undefined;
  /**
   * @member {Number} leader_money
   */
  exports.prototype['leader_money'] = undefined;
  /**
   * @member {Number} money
   */
  exports.prototype['money'] = undefined;
  /**
   * @member {Number} question_count
   */
  exports.prototype['question_count'] = undefined;
  /**
   * @member {Number} unanswered_question_count
   */
  exports.prototype['unanswered_question_count'] = undefined;



  return exports;
}));


