/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.GroupRequest = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GroupRequest model module.
   * @module model/GroupRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupRequest</code>.
   * @alias module:model/GroupRequest
   * @class
   * @param name {String} 
   * @param uidLeader {String} 
   * @param price {Number} 
   */
  var exports = function(name, uidLeader, price) {
    var _this = this;



    _this['name'] = name;



    _this['uid_leader'] = uidLeader;





    _this['price'] = price;

  };

  /**
   * Constructs a <code>GroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupRequest} obj Optional instance to populate.
   * @return {module:model/GroupRequest} The populated <code>GroupRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('application_id')) {
        obj['application_id'] = ApiClient.convertToType(data['application_id'], 'Number');
      }
      if (data.hasOwnProperty('invite_code')) {
        obj['invite_code'] = ApiClient.convertToType(data['invite_code'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ApiClient.convertToType(data['image'], 'String');
      }
      if (data.hasOwnProperty('summary')) {
        obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
      }
      if (data.hasOwnProperty('welcome')) {
        obj['welcome'] = ApiClient.convertToType(data['welcome'], 'String');
      }
      if (data.hasOwnProperty('uid_leader')) {
        obj['uid_leader'] = ApiClient.convertToType(data['uid_leader'], 'String');
      }
      if (data.hasOwnProperty('leader_name')) {
        obj['leader_name'] = ApiClient.convertToType(data['leader_name'], 'String');
      }
      if (data.hasOwnProperty('leader_summary')) {
        obj['leader_summary'] = ApiClient.convertToType(data['leader_summary'], 'String');
      }
      if (data.hasOwnProperty('leader_phone')) {
        obj['leader_phone'] = ApiClient.convertToType(data['leader_phone'], 'String');
      }
      if (data.hasOwnProperty('leader_weixin')) {
        obj['leader_weixin'] = ApiClient.convertToType(data['leader_weixin'], 'String');
      }
      if (data.hasOwnProperty('realm')) {
        obj['realm'] = ApiClient.convertToType(data['realm'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('category_id')) {
        obj['category_id'] = ApiClient.convertToType(data['category_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} application_id
   */
  exports.prototype['application_id'] = undefined;
  /**
   * @member {Number} invite_code
   */
  exports.prototype['invite_code'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} image
   */
  exports.prototype['image'] = undefined;
  /**
   * @member {String} summary
   */
  exports.prototype['summary'] = undefined;
  /**
   * @member {String} welcome
   */
  exports.prototype['welcome'] = undefined;
  /**
   * @member {String} uid_leader
   */
  exports.prototype['uid_leader'] = undefined;
  /**
   * @member {String} leader_name
   */
  exports.prototype['leader_name'] = undefined;
  /**
   * @member {String} leader_summary
   */
  exports.prototype['leader_summary'] = undefined;
  /**
   * @member {String} leader_phone
   */
  exports.prototype['leader_phone'] = undefined;
  /**
   * @member {String} leader_weixin
   */
  exports.prototype['leader_weixin'] = undefined;
  /**
   * @member {String} realm
   */
  exports.prototype['realm'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {Number} category_id
   */
  exports.prototype['category_id'] = undefined;



  return exports;
}));


