/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BasicShare', 'model/CategoryResponse', 'model/GroupExtraData', 'model/GroupStatistics', 'model/MemberUserResponse', 'model/SimpleUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BasicShare'), require('./CategoryResponse'), require('./GroupExtraData'), require('./GroupStatistics'), require('./MemberUserResponse'), require('./SimpleUser'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.GroupCheckResponse = factory(root.Mimir.ApiClient, root.Mimir.BasicShare, root.Mimir.CategoryResponse, root.Mimir.GroupExtraData, root.Mimir.GroupStatistics, root.Mimir.MemberUserResponse, root.Mimir.SimpleUser);
  }
}(this, function(ApiClient, BasicShare, CategoryResponse, GroupExtraData, GroupStatistics, MemberUserResponse, SimpleUser) {
  'use strict';




  /**
   * The GroupCheckResponse model module.
   * @module model/GroupCheckResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupCheckResponse</code>.
   * @alias module:model/GroupCheckResponse
   * @class
   * @extends module:model/GroupExtraData
   */
  var exports = function() {
    var _this = this;
    GroupExtraData.call(_this);



  };

  /**
   * Constructs a <code>GroupCheckResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupCheckResponse} obj Optional instance to populate.
   * @return {module:model/GroupCheckResponse} The populated <code>GroupCheckResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      GroupExtraData.constructFromObject(data, obj);
      if (data.hasOwnProperty('info_is_checking')) {
        obj['info_is_checking'] = ApiClient.convertToType(data['info_is_checking'], 'Boolean');
      }
      if (data.hasOwnProperty('intro_is_checking')) {
        obj['intro_is_checking'] = ApiClient.convertToType(data['intro_is_checking'], 'Boolean');
      }
      if (data.hasOwnProperty('is_in_whitelist')) {
        obj['is_in_whitelist'] = ApiClient.convertToType(data['is_in_whitelist'], 'Boolean');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(GroupExtraData.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Boolean} info_is_checking
   */
  exports.prototype['info_is_checking'] = undefined;
  /**
   * @member {Boolean} intro_is_checking
   */
  exports.prototype['intro_is_checking'] = undefined;
  /**
   * @member {Boolean} is_in_whitelist
   * @default false
   */
  exports.prototype['is_in_whitelist'] = false;



  return exports;
}));


