/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CachedAwardResponse', 'model/CachedReplyResponse', 'model/PrivilegeGroup', 'model/QuestionResponse', 'model/RichShareContent', 'model/ShareItem', 'model/ShareStatistics', 'model/ShareUserStatistics', 'model/SimpleUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CachedAwardResponse'), require('./CachedReplyResponse'), require('./PrivilegeGroup'), require('./QuestionResponse'), require('./RichShareContent'), require('./ShareItem'), require('./ShareStatistics'), require('./ShareUserStatistics'), require('./SimpleUser'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.GroupShareItem = factory(root.Mimir.ApiClient, root.Mimir.CachedAwardResponse, root.Mimir.CachedReplyResponse, root.Mimir.PrivilegeGroup, root.Mimir.QuestionResponse, root.Mimir.RichShareContent, root.Mimir.ShareItem, root.Mimir.ShareStatistics, root.Mimir.ShareUserStatistics, root.Mimir.SimpleUser);
  }
}(this, function(ApiClient, CachedAwardResponse, CachedReplyResponse, PrivilegeGroup, QuestionResponse, RichShareContent, ShareItem, ShareStatistics, ShareUserStatistics, SimpleUser) {
  'use strict';




  /**
   * The GroupShareItem model module.
   * @module model/GroupShareItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GroupShareItem</code>.
   * @alias module:model/GroupShareItem
   * @class
   * @extends module:model/ShareItem
   */
  var exports = function() {
    var _this = this;
    ShareItem.call(_this);

  };

  /**
   * Constructs a <code>GroupShareItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupShareItem} obj Optional instance to populate.
   * @return {module:model/GroupShareItem} The populated <code>GroupShareItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ShareItem.constructFromObject(data, obj);
      if (data.hasOwnProperty('group')) {
        obj['group'] = PrivilegeGroup.constructFromObject(data['group']);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(ShareItem.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/PrivilegeGroup} group
   */
  exports.prototype['group'] = undefined;



  return exports;
}));


