/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.MemberResponse = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MemberResponse model module.
   * @module model/MemberResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MemberResponse</code>.
   * @alias module:model/MemberResponse
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>MemberResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MemberResponse} obj Optional instance to populate.
   * @return {module:model/MemberResponse} The populated <code>MemberResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('uid')) {
        obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
      }
      if (data.hasOwnProperty('group_id')) {
        obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Number');
      }
      if (data.hasOwnProperty('end_at')) {
        obj['end_at'] = ApiClient.convertToType(data['end_at'], 'Date');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('is_effective')) {
        obj['is_effective'] = ApiClient.convertToType(data['is_effective'], 'Boolean');
      }
      if (data.hasOwnProperty('is_prisoner')) {
        obj['is_prisoner'] = ApiClient.convertToType(data['is_prisoner'], 'Boolean');
      }
      if (data.hasOwnProperty('jail_at')) {
        obj['jail_at'] = ApiClient.convertToType(data['jail_at'], 'Date');
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} uid
   */
  exports.prototype['uid'] = undefined;
  /**
   * @member {Number} group_id
   */
  exports.prototype['group_id'] = undefined;
  /**
   * @member {Date} end_at
   */
  exports.prototype['end_at'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Boolean} is_effective
   */
  exports.prototype['is_effective'] = undefined;
  /**
   * @member {Boolean} is_prisoner
   */
  exports.prototype['is_prisoner'] = undefined;
  /**
   * @member {Date} jail_at
   */
  exports.prototype['jail_at'] = undefined;
  /**
   * @member {String} role
   */
  exports.prototype['role'] = undefined;



  return exports;
}));


