/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserAvatar'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserAvatar'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.MemberStatisticsResponse = factory(root.Mimir.ApiClient, root.Mimir.UserAvatar);
  }
}(this, function(ApiClient, UserAvatar) {
  'use strict';




  /**
   * The MemberStatisticsResponse model module.
   * @module model/MemberStatisticsResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MemberStatisticsResponse</code>.
   * @alias module:model/MemberStatisticsResponse
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>MemberStatisticsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MemberStatisticsResponse} obj Optional instance to populate.
   * @return {module:model/MemberStatisticsResponse} The populated <code>MemberStatisticsResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('nickname')) {
        obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('is_title_authorization')) {
        obj['is_title_authorization'] = ApiClient.convertToType(data['is_title_authorization'], 'Boolean');
      }
      if (data.hasOwnProperty('avatar')) {
        obj['avatar'] = UserAvatar.constructFromObject(data['avatar']);
      }
      if (data.hasOwnProperty('group_id')) {
        obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Number');
      }
      if (data.hasOwnProperty('left_days')) {
        obj['left_days'] = ApiClient.convertToType(data['left_days'], 'Number');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('buy_months')) {
        obj['buy_months'] = ApiClient.convertToType(data['buy_months'], 'Number');
      }
      if (data.hasOwnProperty('interactive_count')) {
        obj['interactive_count'] = ApiClient.convertToType(data['interactive_count'], 'Number');
      }
      if (data.hasOwnProperty('averge_interactive_count')) {
        obj['averge_interactive_count'] = ApiClient.convertToType(data['averge_interactive_count'], 'Number');
      }
      if (data.hasOwnProperty('payout')) {
        obj['payout'] = ApiClient.convertToType(data['payout'], 'Number');
      }
      if (data.hasOwnProperty('averge_payout')) {
        obj['averge_payout'] = ApiClient.convertToType(data['averge_payout'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} nickname
   */
  exports.prototype['nickname'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {Boolean} is_title_authorization
   */
  exports.prototype['is_title_authorization'] = undefined;
  /**
   * @member {module:model/UserAvatar} avatar
   */
  exports.prototype['avatar'] = undefined;
  /**
   * @member {Number} group_id
   */
  exports.prototype['group_id'] = undefined;
  /**
   * @member {Number} left_days
   */
  exports.prototype['left_days'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Number} buy_months
   */
  exports.prototype['buy_months'] = undefined;
  /**
   * @member {Number} interactive_count
   */
  exports.prototype['interactive_count'] = undefined;
  /**
   * @member {Number} averge_interactive_count
   */
  exports.prototype['averge_interactive_count'] = undefined;
  /**
   * @member {Number} payout
   */
  exports.prototype['payout'] = undefined;
  /**
   * @member {Number} averge_payout
   */
  exports.prototype['averge_payout'] = undefined;



  return exports;
}));


