/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PfopPipline'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PfopPipline'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.PfopNotifyRequest = factory(root.Mimir.ApiClient, root.Mimir.PfopPipline);
  }
}(this, function(ApiClient, PfopPipline) {
  'use strict';




  /**
   * The PfopNotifyRequest model module.
   * @module model/PfopNotifyRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PfopNotifyRequest</code>.
   * @alias module:model/PfopNotifyRequest
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>PfopNotifyRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PfopNotifyRequest} obj Optional instance to populate.
   * @return {module:model/PfopNotifyRequest} The populated <code>PfopNotifyRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'Number');
      }
      if (data.hasOwnProperty('desc')) {
        obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
      }
      if (data.hasOwnProperty('inputKey')) {
        obj['inputKey'] = ApiClient.convertToType(data['inputKey'], 'String');
      }
      if (data.hasOwnProperty('inputBucket')) {
        obj['inputBucket'] = ApiClient.convertToType(data['inputBucket'], 'String');
      }
      if (data.hasOwnProperty('pipline')) {
        obj['pipline'] = ApiClient.convertToType(data['pipline'], 'String');
      }
      if (data.hasOwnProperty('reqid')) {
        obj['reqid'] = ApiClient.convertToType(data['reqid'], 'String');
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [PfopPipline]);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} code
   */
  exports.prototype['code'] = undefined;
  /**
   * @member {String} desc
   */
  exports.prototype['desc'] = undefined;
  /**
   * @member {String} inputKey
   */
  exports.prototype['inputKey'] = undefined;
  /**
   * @member {String} inputBucket
   */
  exports.prototype['inputBucket'] = undefined;
  /**
   * @member {String} pipline
   */
  exports.prototype['pipline'] = undefined;
  /**
   * @member {String} reqid
   */
  exports.prototype['reqid'] = undefined;
  /**
   * @member {Array.<module:model/PfopPipline>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


