/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.QiniuTokenResponse = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The QiniuTokenResponse model module.
   * @module model/QiniuTokenResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>QiniuTokenResponse</code>.
   * @alias module:model/QiniuTokenResponse
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>QiniuTokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QiniuTokenResponse} obj Optional instance to populate.
   * @return {module:model/QiniuTokenResponse} The populated <code>QiniuTokenResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('domain')) {
        obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
      }
      if (data.hasOwnProperty('upload_url')) {
        obj['upload_url'] = ApiClient.convertToType(data['upload_url'], 'String');
      }
      if (data.hasOwnProperty('https_upload_url')) {
        obj['https_upload_url'] = ApiClient.convertToType(data['https_upload_url'], 'String');
      }
      if (data.hasOwnProperty('token')) {
        obj['token'] = ApiClient.convertToType(data['token'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} domain
   * @default ''
   */
  exports.prototype['domain'] = '';
  /**
   * @member {String} upload_url
   * @default ''
   */
  exports.prototype['upload_url'] = '';
  /**
   * @member {String} https_upload_url
   * @default ''
   */
  exports.prototype['https_upload_url'] = '';
  /**
   * @member {String} token
   * @default ''
   */
  exports.prototype['token'] = '';



  return exports;
}));


