/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.RechargeResponse = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RechargeResponse model module.
   * @module model/RechargeResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RechargeResponse</code>.
   * @alias module:model/RechargeResponse
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>RechargeResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RechargeResponse} obj Optional instance to populate.
   * @return {module:model/RechargeResponse} The populated <code>RechargeResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('api_url')) {
        obj['api_url'] = ApiClient.convertToType(data['api_url'], 'String');
      }
      if (data.hasOwnProperty('out_trade_no')) {
        obj['out_trade_no'] = ApiClient.convertToType(data['out_trade_no'], 'String');
      }
      if (data.hasOwnProperty('order_type')) {
        obj['order_type'] = ApiClient.convertToType(data['order_type'], 'String');
      }
      if (data.hasOwnProperty('notify_url')) {
        obj['notify_url'] = ApiClient.convertToType(data['notify_url'], 'String');
      }
      if (data.hasOwnProperty('product_id')) {
        obj['product_id'] = ApiClient.convertToType(data['product_id'], 'String');
      }
      if (data.hasOwnProperty('charge')) {
        obj['charge'] = ApiClient.convertToType(data['charge'], 'Number');
      }
      if (data.hasOwnProperty('remote_action_id')) {
        obj['remote_action_id'] = ApiClient.convertToType(data['remote_action_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} api_url
   */
  exports.prototype['api_url'] = undefined;
  /**
   * @member {String} out_trade_no
   */
  exports.prototype['out_trade_no'] = undefined;
  /**
   * @member {String} order_type
   */
  exports.prototype['order_type'] = undefined;
  /**
   * @member {String} notify_url
   */
  exports.prototype['notify_url'] = undefined;
  /**
   * @member {String} product_id
   */
  exports.prototype['product_id'] = undefined;
  /**
   * @member {Number} charge
   */
  exports.prototype['charge'] = undefined;
  /**
   * @member {Number} remote_action_id
   */
  exports.prototype['remote_action_id'] = undefined;



  return exports;
}));


