/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.RechargeRequest = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RechargeRequest model module.
   * @module model/RechargeRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RechargeRequest</code>.
   * @alias module:model/RechargeRequest
   * @class
   * @param charge {Number} 
   * @param tradeType {module:model/RechargeRequest.TradeTypeEnum} 
   * @param productId {module:model/RechargeRequest.ProductIdEnum} 
   */
  var exports = function(charge, tradeType, productId) {
    var _this = this;

    _this['charge'] = charge;
    _this['trade_type'] = tradeType;
    _this['product_id'] = productId;


  };

  /**
   * Constructs a <code>RechargeRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RechargeRequest} obj Optional instance to populate.
   * @return {module:model/RechargeRequest} The populated <code>RechargeRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('charge')) {
        obj['charge'] = ApiClient.convertToType(data['charge'], 'Number');
      }
      if (data.hasOwnProperty('trade_type')) {
        obj['trade_type'] = ApiClient.convertToType(data['trade_type'], 'String');
      }
      if (data.hasOwnProperty('product_id')) {
        obj['product_id'] = ApiClient.convertToType(data['product_id'], 'String');
      }
      if (data.hasOwnProperty('client')) {
        obj['client'] = ApiClient.convertToType(data['client'], 'String');
      }
      if (data.hasOwnProperty('after')) {
        obj['after'] = ApiClient.convertToType(data['after'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} charge
   */
  exports.prototype['charge'] = undefined;
  /**
   * @member {module:model/RechargeRequest.TradeTypeEnum} trade_type
   */
  exports.prototype['trade_type'] = undefined;
  /**
   * @member {module:model/RechargeRequest.ProductIdEnum} product_id
   */
  exports.prototype['product_id'] = undefined;
  /**
   * @member {module:model/RechargeRequest.ClientEnum} client
   * @default 'default'
   */
  exports.prototype['client'] = 'default';
  /**
   * @member {String} after
   */
  exports.prototype['after'] = undefined;


  /**
   * Allowed values for the <code>trade_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TradeTypeEnum = {
    /**
     * value: "APP"
     * @const
     */
    "APP": "APP",
    /**
     * value: "JSAPI"
     * @const
     */
    "JSAPI": "JSAPI",
    /**
     * value: "NATIVE"
     * @const
     */
    "NATIVE": "NATIVE"  };

  /**
   * Allowed values for the <code>product_id</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ProductIdEnum = {
    /**
     * value: "com.fantuan.gpay_test"
     * @const
     */
    "test": "com.fantuan.gpay_test",
    /**
     * value: "com.fantuan.gpay_free"
     * @const
     */
    "free": "com.fantuan.gpay_free",
    /**
     * value: "com.fantuan.gpay_one"
     * @const
     */
    "one": "com.fantuan.gpay_one",
    /**
     * value: "com.fantuan.gpay_ten"
     * @const
     */
    "ten": "com.fantuan.gpay_ten",
    /**
     * value: "com.fantuan.gpay_twenty"
     * @const
     */
    "twenty": "com.fantuan.gpay_twenty",
    /**
     * value: "com.fantuan.gpay_fifty"
     * @const
     */
    "fifty": "com.fantuan.gpay_fifty",
    /**
     * value: "com.fantuan.gpay_onehundred"
     * @const
     */
    "onehundred": "com.fantuan.gpay_onehundred",
    /**
     * value: "com.fantuan.gpay_threehundred"
     * @const
     */
    "threehundred": "com.fantuan.gpay_threehundred",
    /**
     * value: "com.fantuan.gpay_fivehundred"
     * @const
     */
    "fivehundred": "com.fantuan.gpay_fivehundred"  };

  /**
   * Allowed values for the <code>client</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ClientEnum = {
    /**
     * value: "ios"
     * @const
     */
    "ios": "ios",
    /**
     * value: "android"
     * @const
     */
    "android": "android",
    /**
     * value: "web"
     * @const
     */
    "web": "web",
    /**
     * value: "iap"
     * @const
     */
    "iap": "iap",
    /**
     * value: "default"
     * @const
     */
    "default": "default"  };


  return exports;
}));


