/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.ReplyRequest = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ReplyRequest model module.
   * @module model/ReplyRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ReplyRequest</code>.
   * @alias module:model/ReplyRequest
   * @class
   * @param uidAuthor {String} 
   * @param text {String} 
   */
  var exports = function(uidAuthor, text) {
    var _this = this;

    _this['uid_author'] = uidAuthor;
    _this['text'] = text;


  };

  /**
   * Constructs a <code>ReplyRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReplyRequest} obj Optional instance to populate.
   * @return {module:model/ReplyRequest} The populated <code>ReplyRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uid_author')) {
        obj['uid_author'] = ApiClient.convertToType(data['uid_author'], 'String');
      }
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('related_id')) {
        obj['related_id'] = ApiClient.convertToType(data['related_id'], 'Number');
      }
      if (data.hasOwnProperty('parent_id')) {
        obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} uid_author
   */
  exports.prototype['uid_author'] = undefined;
  /**
   * @member {String} text
   * @default ''
   */
  exports.prototype['text'] = '';
  /**
   * @member {Number} related_id
   */
  exports.prototype['related_id'] = undefined;
  /**
   * @member {Number} parent_id
   */
  exports.prototype['parent_id'] = undefined;



  return exports;
}));


