/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthorItem', 'model/AwardResponse', 'model/BasicShare', 'model/ReplyMemberInfo', 'model/ReplyQuoteItem', 'model/RichShareContent', 'model/ShareAuthorPrivilege', 'model/ShareAwardsItems', 'model/ShareStatistics', 'model/ShareStatisticsItem', 'model/SimpleUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AuthorItem'), require('./AwardResponse'), require('./BasicShare'), require('./ReplyMemberInfo'), require('./ReplyQuoteItem'), require('./RichShareContent'), require('./ShareAuthorPrivilege'), require('./ShareAwardsItems'), require('./ShareStatistics'), require('./ShareStatisticsItem'), require('./SimpleUser'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.ReplyResponse = factory(root.Mimir.ApiClient, root.Mimir.AuthorItem, root.Mimir.AwardResponse, root.Mimir.BasicShare, root.Mimir.ReplyMemberInfo, root.Mimir.ReplyQuoteItem, root.Mimir.RichShareContent, root.Mimir.ShareAuthorPrivilege, root.Mimir.ShareAwardsItems, root.Mimir.ShareStatistics, root.Mimir.ShareStatisticsItem, root.Mimir.SimpleUser);
  }
}(this, function(ApiClient, AuthorItem, AwardResponse, BasicShare, ReplyMemberInfo, ReplyQuoteItem, RichShareContent, ShareAuthorPrivilege, ShareAwardsItems, ShareStatistics, ShareStatisticsItem, SimpleUser) {
  'use strict';




  /**
   * The ReplyResponse model module.
   * @module model/ReplyResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ReplyResponse</code>.
   * @alias module:model/ReplyResponse
   * @class
   * @extends module:model/BasicShare
   * @implements module:model/AuthorItem
   * @implements module:model/ReplyQuoteItem
   * @implements module:model/ReplyMemberInfo
   * @implements module:model/ShareAwardsItems
   * @implements module:model/ShareStatisticsItem
   * @implements module:model/ShareAuthorPrivilege
   */
  var exports = function() {
    var _this = this;
    BasicShare.call(_this);
    AuthorItem.call(_this);
    ReplyQuoteItem.call(_this);
    ReplyMemberInfo.call(_this);
    ShareAwardsItems.call(_this);
    ShareStatisticsItem.call(_this);
    ShareAuthorPrivilege.call(_this);

  };

  /**
   * Constructs a <code>ReplyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReplyResponse} obj Optional instance to populate.
   * @return {module:model/ReplyResponse} The populated <code>ReplyResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      BasicShare.constructFromObject(data, obj);
      AuthorItem.constructFromObject(data, obj);
      ReplyQuoteItem.constructFromObject(data, obj);
      ReplyMemberInfo.constructFromObject(data, obj);
      ShareAwardsItems.constructFromObject(data, obj);
      ShareStatisticsItem.constructFromObject(data, obj);
      ShareAuthorPrivilege.constructFromObject(data, obj);
      if (data.hasOwnProperty('is_awarded_by_leader')) {
        obj['is_awarded_by_leader'] = ApiClient.convertToType(data['is_awarded_by_leader'], 'Boolean');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(BasicShare.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Boolean} is_awarded_by_leader
   */
  exports.prototype['is_awarded_by_leader'] = undefined;

  // Implement AuthorItem interface:
  /**
   * @member {module:model/SimpleUser} author
   */
exports.prototype['author'] = undefined;

  // Implement ReplyQuoteItem interface:
  /**
   * @member {module:model/SimpleUser} quote
   */
exports.prototype['quote'] = undefined;

  /**
   * @member {Boolean} is_quote_author_great
   */
exports.prototype['is_quote_author_great'] = undefined;

  // Implement ReplyMemberInfo interface:
  /**
   * @member {Boolean} is_prisoner
   */
exports.prototype['is_prisoner'] = undefined;

  // Implement ShareAwardsItems interface:
  /**
   * @member {Array.<module:model/AwardResponse>} awards
   */
exports.prototype['awards'] = undefined;

  // Implement ShareStatisticsItem interface:
  /**
   * @member {module:model/ShareStatistics} statistics
   */
exports.prototype['statistics'] = undefined;

  // Implement ShareAuthorPrivilege interface:
  /**
   * @member {Boolean} author_is_up_guest
   */
exports.prototype['author_is_up_guest'] = undefined;



  return exports;
}));


