/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.RichShareContent = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RichShareContent model module.
   * @module model/RichShareContent
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RichShareContent</code>.
   * @alias module:model/RichShareContent
   * @class
   */
  var exports = function() {
    var _this = this;


















  };

  /**
   * Constructs a <code>RichShareContent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RichShareContent} obj Optional instance to populate.
   * @return {module:model/RichShareContent} The populated <code>RichShareContent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('link')) {
        obj['link'] = ApiClient.convertToType(data['link'], 'String');
      }
      if (data.hasOwnProperty('summary')) {
        obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ApiClient.convertToType(data['image'], 'String');
      }
      if (data.hasOwnProperty('voice')) {
        obj['voice'] = ApiClient.convertToType(data['voice'], 'String');
      }
      if (data.hasOwnProperty('video')) {
        obj['video'] = ApiClient.convertToType(data['video'], 'String');
      }
      if (data.hasOwnProperty('shop')) {
        obj['shop'] = ApiClient.convertToType(data['shop'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'String');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
      }
      if (data.hasOwnProperty('article_type')) {
        obj['article_type'] = ApiClient.convertToType(data['article_type'], 'String');
      }
      if (data.hasOwnProperty('author')) {
        obj['author'] = ApiClient.convertToType(data['author'], 'String');
      }
      if (data.hasOwnProperty('grade')) {
        obj['grade'] = ApiClient.convertToType(data['grade'], 'Number');
      }
      if (data.hasOwnProperty('director')) {
        obj['director'] = ApiClient.convertToType(data['director'], 'String');
      }
      if (data.hasOwnProperty('lead_actor')) {
        obj['lead_actor'] = ApiClient.convertToType(data['lead_actor'], 'String');
      }
      if (data.hasOwnProperty('original_title')) {
        obj['original_title'] = ApiClient.convertToType(data['original_title'], 'String');
      }
      if (data.hasOwnProperty('category')) {
        obj['category'] = ApiClient.convertToType(data['category'], 'String');
      }
      if (data.hasOwnProperty('year')) {
        obj['year'] = ApiClient.convertToType(data['year'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} title
   * @default ''
   */
  exports.prototype['title'] = '';
  /**
   * @member {String} link
   * @default ''
   */
  exports.prototype['link'] = '';
  /**
   * @member {String} summary
   * @default ''
   */
  exports.prototype['summary'] = '';
  /**
   * @member {String} image
   * @default ''
   */
  exports.prototype['image'] = '';
  /**
   * @member {String} voice
   * @default ''
   */
  exports.prototype['voice'] = '';
  /**
   * @member {String} video
   * @default ''
   */
  exports.prototype['video'] = '';
  /**
   * @member {String} shop
   * @default ''
   */
  exports.prototype['shop'] = '';
  /**
   * @member {String} price
   * @default ''
   */
  exports.prototype['price'] = '';
  /**
   * @member {Number} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * @member {module:model/RichShareContent.ArticleTypeEnum} article_type
   * @default 'common'
   */
  exports.prototype['article_type'] = 'common';
  /**
   * @member {String} author
   * @default ''
   */
  exports.prototype['author'] = '';
  /**
   * @member {Number} grade
   */
  exports.prototype['grade'] = undefined;
  /**
   * @member {String} director
   * @default ''
   */
  exports.prototype['director'] = '';
  /**
   * @member {String} lead_actor
   * @default ''
   */
  exports.prototype['lead_actor'] = '';
  /**
   * @member {String} original_title
   * @default ''
   */
  exports.prototype['original_title'] = '';
  /**
   * @member {String} category
   * @default ''
   */
  exports.prototype['category'] = '';
  /**
   * @member {String} year
   * @default ''
   */
  exports.prototype['year'] = '';


  /**
   * Allowed values for the <code>article_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ArticleTypeEnum = {
    /**
     * value: "common"
     * @const
     */
    "common": "common",
    /**
     * value: "doubanbook"
     * @const
     */
    "doubanbook": "doubanbook",
    /**
     * value: "doubanmovie"
     * @const
     */
    "doubanmovie": "doubanmovie",
    /**
     * value: "doubanmusic"
     * @const
     */
    "doubanmusic": "doubanmusic",
    /**
     * value: "youzan"
     * @const
     */
    "youzan": "youzan",
    /**
     * value: "weidian"
     * @const
     */
    "weidian": "weidian"  };


  return exports;
}));


