/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthorItem', 'model/BasicShare', 'model/CachedAwardResponse', 'model/CachedReplyResponse', 'model/QuestionItem', 'model/QuestionResponse', 'model/RichShareContent', 'model/ShareStatistics', 'model/ShareStatisticsItem', 'model/ShareUserFavoriteItem', 'model/ShareUserStatistics', 'model/ShareUserStatisticsItem', 'model/SimpleUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AuthorItem'), require('./BasicShare'), require('./CachedAwardResponse'), require('./CachedReplyResponse'), require('./QuestionItem'), require('./QuestionResponse'), require('./RichShareContent'), require('./ShareStatistics'), require('./ShareStatisticsItem'), require('./ShareUserFavoriteItem'), require('./ShareUserStatistics'), require('./ShareUserStatisticsItem'), require('./SimpleUser'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.ShareItem = factory(root.Mimir.ApiClient, root.Mimir.AuthorItem, root.Mimir.BasicShare, root.Mimir.CachedAwardResponse, root.Mimir.CachedReplyResponse, root.Mimir.QuestionItem, root.Mimir.QuestionResponse, root.Mimir.RichShareContent, root.Mimir.ShareStatistics, root.Mimir.ShareStatisticsItem, root.Mimir.ShareUserFavoriteItem, root.Mimir.ShareUserStatistics, root.Mimir.ShareUserStatisticsItem, root.Mimir.SimpleUser);
  }
}(this, function(ApiClient, AuthorItem, BasicShare, CachedAwardResponse, CachedReplyResponse, QuestionItem, QuestionResponse, RichShareContent, ShareStatistics, ShareStatisticsItem, ShareUserFavoriteItem, ShareUserStatistics, ShareUserStatisticsItem, SimpleUser) {
  'use strict';




  /**
   * The ShareItem model module.
   * @module model/ShareItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ShareItem</code>.
   * @alias module:model/ShareItem
   * @class
   * @extends module:model/QuestionItem
   * @implements module:model/BasicShare
   * @implements module:model/AuthorItem
   * @implements module:model/ShareStatisticsItem
   * @implements module:model/ShareUserStatisticsItem
   * @implements module:model/ShareUserFavoriteItem
   */
  var exports = function() {
    var _this = this;
    QuestionItem.call(_this);
    BasicShare.call(_this);
    AuthorItem.call(_this);
    ShareStatisticsItem.call(_this);
    ShareUserStatisticsItem.call(_this);
    ShareUserFavoriteItem.call(_this);



  };

  /**
   * Constructs a <code>ShareItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShareItem} obj Optional instance to populate.
   * @return {module:model/ShareItem} The populated <code>ShareItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      QuestionItem.constructFromObject(data, obj);
      BasicShare.constructFromObject(data, obj);
      AuthorItem.constructFromObject(data, obj);
      ShareStatisticsItem.constructFromObject(data, obj);
      ShareUserStatisticsItem.constructFromObject(data, obj);
      ShareUserFavoriteItem.constructFromObject(data, obj);
      if (data.hasOwnProperty('awards')) {
        obj['awards'] = ApiClient.convertToType(data['awards'], [CachedAwardResponse]);
      }
      if (data.hasOwnProperty('replies')) {
        obj['replies'] = ApiClient.convertToType(data['replies'], [CachedReplyResponse]);
      }
      if (data.hasOwnProperty('recommends')) {
        obj['recommends'] = ApiClient.convertToType(data['recommends'], [CachedReplyResponse]);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(QuestionItem.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Array.<module:model/CachedAwardResponse>} awards
   */
  exports.prototype['awards'] = undefined;
  /**
   * @member {Array.<module:model/CachedReplyResponse>} replies
   */
  exports.prototype['replies'] = undefined;
  /**
   * @member {Array.<module:model/CachedReplyResponse>} recommends
   */
  exports.prototype['recommends'] = undefined;

  // Implement BasicShare interface:
  /**
   * @member {Number} id
   */
exports.prototype['id'] = undefined;

  /**
   * @member {Number} group_id
   */
exports.prototype['group_id'] = undefined;

  /**
   * @member {String} title
   * @default ''
   */
exports.prototype['title'] = '';

  /**
   * @member {String} uid_author
   * @default ''
   */
exports.prototype['uid_author'] = '';

  /**
   * @member {String} reply_reference
   * @default ''
   */
exports.prototype['reply_reference'] = '';

  /**
   * @member {Boolean} is_check
   * @default true
   */
exports.prototype['is_check'] = true;

  /**
   * @member {module:model/BasicShare.ContentTypeEnum} content_type
   */
exports.prototype['content_type'] = undefined;

  /**
   * @member {module:model/BasicShare.ShareTypeEnum} share_type
   */
exports.prototype['share_type'] = undefined;

  /**
   * @member {String} text
   * @default ''
   */
exports.prototype['text'] = '';

  /**
   * @member {Array.<module:model/RichShareContent>} links
   */
exports.prototype['links'] = undefined;

  /**
   * @member {Number} related_id
   */
exports.prototype['related_id'] = undefined;

  /**
   * @member {Number} parent_id
   */
exports.prototype['parent_id'] = undefined;

  /**
   * @member {Boolean} is_recommended
   */
exports.prototype['is_recommended'] = undefined;

  /**
   * @member {Boolean} is_from_leader
   */
exports.prototype['is_from_leader'] = undefined;

  /**
   * @member {Boolean} is_top
   */
exports.prototype['is_top'] = undefined;

  /**
   * @member {Date} created_at
   */
exports.prototype['created_at'] = undefined;

  /**
   * @member {String} question_content
   * @default ''
   */
exports.prototype['question_content'] = '';

  /**
   * @member {Number} words_num
   */
exports.prototype['words_num'] = undefined;

  // Implement AuthorItem interface:
  /**
   * @member {module:model/SimpleUser} author
   */
exports.prototype['author'] = undefined;

  // Implement ShareStatisticsItem interface:
  /**
   * @member {module:model/ShareStatistics} statistics
   */
exports.prototype['statistics'] = undefined;

  // Implement ShareUserStatisticsItem interface:
  /**
   * @member {module:model/ShareUserStatistics} current_user_statistics
   */
exports.prototype['current_user_statistics'] = undefined;

  // Implement ShareUserFavoriteItem interface:
  /**
   * @member {Boolean} current_user_favorite
   * @default false
   */
exports.prototype['current_user_favorite'] = false;



  return exports;
}));


