/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthorItem', 'model/BasicShare', 'model/PrivilegeGroup', 'model/RichShareContent', 'model/ShareGroupItem', 'model/ShareStatistics', 'model/ShareStatisticsItem', 'model/ShareUserFavoriteItem', 'model/ShareUserStatistics', 'model/ShareUserStatisticsItem', 'model/SimpleUser', 'model/TagResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AuthorItem'), require('./BasicShare'), require('./PrivilegeGroup'), require('./RichShareContent'), require('./ShareGroupItem'), require('./ShareStatistics'), require('./ShareStatisticsItem'), require('./ShareUserFavoriteItem'), require('./ShareUserStatistics'), require('./ShareUserStatisticsItem'), require('./SimpleUser'), require('./TagResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.ShareResponse = factory(root.Mimir.ApiClient, root.Mimir.AuthorItem, root.Mimir.BasicShare, root.Mimir.PrivilegeGroup, root.Mimir.RichShareContent, root.Mimir.ShareGroupItem, root.Mimir.ShareStatistics, root.Mimir.ShareStatisticsItem, root.Mimir.ShareUserFavoriteItem, root.Mimir.ShareUserStatistics, root.Mimir.ShareUserStatisticsItem, root.Mimir.SimpleUser, root.Mimir.TagResponse);
  }
}(this, function(ApiClient, AuthorItem, BasicShare, PrivilegeGroup, RichShareContent, ShareGroupItem, ShareStatistics, ShareStatisticsItem, ShareUserFavoriteItem, ShareUserStatistics, ShareUserStatisticsItem, SimpleUser, TagResponse) {
  'use strict';




  /**
   * The ShareResponse model module.
   * @module model/ShareResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ShareResponse</code>.
   * @alias module:model/ShareResponse
   * @class
   * @extends module:model/BasicShare
   * @implements module:model/AuthorItem
   * @implements module:model/ShareGroupItem
   * @implements module:model/ShareStatisticsItem
   * @implements module:model/ShareUserStatisticsItem
   * @implements module:model/ShareUserFavoriteItem
   */
  var exports = function() {
    var _this = this;
    BasicShare.call(_this);
    AuthorItem.call(_this);
    ShareGroupItem.call(_this);
    ShareStatisticsItem.call(_this);
    ShareUserStatisticsItem.call(_this);
    ShareUserFavoriteItem.call(_this);

  };

  /**
   * Constructs a <code>ShareResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShareResponse} obj Optional instance to populate.
   * @return {module:model/ShareResponse} The populated <code>ShareResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      BasicShare.constructFromObject(data, obj);
      AuthorItem.constructFromObject(data, obj);
      ShareGroupItem.constructFromObject(data, obj);
      ShareStatisticsItem.constructFromObject(data, obj);
      ShareUserStatisticsItem.constructFromObject(data, obj);
      ShareUserFavoriteItem.constructFromObject(data, obj);
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [TagResponse]);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(BasicShare.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Array.<module:model/TagResponse>} tags
   */
  exports.prototype['tags'] = undefined;

  // Implement AuthorItem interface:
  /**
   * @member {module:model/SimpleUser} author
   */
exports.prototype['author'] = undefined;

  // Implement ShareGroupItem interface:
  /**
   * @member {module:model/PrivilegeGroup} group
   */
exports.prototype['group'] = undefined;

  // Implement ShareStatisticsItem interface:
  /**
   * @member {module:model/ShareStatistics} statistics
   */
exports.prototype['statistics'] = undefined;

  // Implement ShareUserStatisticsItem interface:
  /**
   * @member {module:model/ShareUserStatistics} current_user_statistics
   */
exports.prototype['current_user_statistics'] = undefined;

  // Implement ShareUserFavoriteItem interface:
  /**
   * @member {Boolean} current_user_favorite
   * @default false
   */
exports.prototype['current_user_favorite'] = false;



  return exports;
}));


