/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BasicShare', 'model/RichShareContent'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BasicShare'), require('./RichShareContent'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.ShareResponseWithoutUser = factory(root.Mimir.ApiClient, root.Mimir.BasicShare, root.Mimir.RichShareContent);
  }
}(this, function(ApiClient, BasicShare, RichShareContent) {
  'use strict';




  /**
   * The ShareResponseWithoutUser model module.
   * @module model/ShareResponseWithoutUser
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ShareResponseWithoutUser</code>.
   * @alias module:model/ShareResponseWithoutUser
   * @class
   * @extends module:model/BasicShare
   */
  var exports = function() {
    var _this = this;
    BasicShare.call(_this);
  };

  /**
   * Constructs a <code>ShareResponseWithoutUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShareResponseWithoutUser} obj Optional instance to populate.
   * @return {module:model/ShareResponseWithoutUser} The populated <code>ShareResponseWithoutUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      BasicShare.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(BasicShare.prototype);
  exports.prototype.constructor = exports;




  return exports;
}));


