/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PrivilegeGroup'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PrivilegeGroup'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.ShareGroupItem = factory(root.Mimir.ApiClient, root.Mimir.PrivilegeGroup);
  }
}(this, function(ApiClient, PrivilegeGroup) {
  'use strict';




  /**
   * The ShareGroupItem model module.
   * @module model/ShareGroupItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ShareGroupItem</code>.
   * @alias module:model/ShareGroupItem
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ShareGroupItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShareGroupItem} obj Optional instance to populate.
   * @return {module:model/ShareGroupItem} The populated <code>ShareGroupItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('group')) {
        obj['group'] = PrivilegeGroup.constructFromObject(data['group']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PrivilegeGroup} group
   */
  exports.prototype['group'] = undefined;



  return exports;
}));


