/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthorItem', 'model/AwardResponse', 'model/BasicShare', 'model/PrivilegeGroup', 'model/QuestionItem', 'model/QuestionResponse', 'model/ReplyResponse', 'model/RichShareContent', 'model/RightToViewShare', 'model/ShareExtraData', 'model/ShareGroupItem', 'model/ShareRecommendsItem', 'model/ShareStatistics', 'model/ShareStatisticsItem', 'model/ShareUserFavoriteItem', 'model/ShareUserStatistics', 'model/ShareUserStatisticsItem', 'model/SimpleUser', 'model/TagResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AuthorItem'), require('./AwardResponse'), require('./BasicShare'), require('./PrivilegeGroup'), require('./QuestionItem'), require('./QuestionResponse'), require('./ReplyResponse'), require('./RichShareContent'), require('./RightToViewShare'), require('./ShareExtraData'), require('./ShareGroupItem'), require('./ShareRecommendsItem'), require('./ShareStatistics'), require('./ShareStatisticsItem'), require('./ShareUserFavoriteItem'), require('./ShareUserStatistics'), require('./ShareUserStatisticsItem'), require('./SimpleUser'), require('./TagResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.ShareCard = factory(root.Mimir.ApiClient, root.Mimir.AuthorItem, root.Mimir.AwardResponse, root.Mimir.BasicShare, root.Mimir.PrivilegeGroup, root.Mimir.QuestionItem, root.Mimir.QuestionResponse, root.Mimir.ReplyResponse, root.Mimir.RichShareContent, root.Mimir.RightToViewShare, root.Mimir.ShareExtraData, root.Mimir.ShareGroupItem, root.Mimir.ShareRecommendsItem, root.Mimir.ShareStatistics, root.Mimir.ShareStatisticsItem, root.Mimir.ShareUserFavoriteItem, root.Mimir.ShareUserStatistics, root.Mimir.ShareUserStatisticsItem, root.Mimir.SimpleUser, root.Mimir.TagResponse);
  }
}(this, function(ApiClient, AuthorItem, AwardResponse, BasicShare, PrivilegeGroup, QuestionItem, QuestionResponse, ReplyResponse, RichShareContent, RightToViewShare, ShareExtraData, ShareGroupItem, ShareRecommendsItem, ShareStatistics, ShareStatisticsItem, ShareUserFavoriteItem, ShareUserStatistics, ShareUserStatisticsItem, SimpleUser, TagResponse) {
  'use strict';




  /**
   * The ShareCard model module.
   * @module model/ShareCard
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ShareCard</code>.
   * @alias module:model/ShareCard
   * @class
   * @extends module:model/QuestionItem
   * @implements module:model/BasicShare
   * @implements module:model/AuthorItem
   * @implements module:model/ShareGroupItem
   * @implements module:model/RightToViewShare
   * @implements module:model/ShareStatisticsItem
   * @implements module:model/ShareRecommendsItem
   * @implements module:model/ShareExtraData
   * @implements module:model/ShareUserStatisticsItem
   * @implements module:model/ShareUserFavoriteItem
   */
  var exports = function() {
    var _this = this;
    QuestionItem.call(_this);
    BasicShare.call(_this);
    AuthorItem.call(_this);
    ShareGroupItem.call(_this);
    RightToViewShare.call(_this);
    ShareStatisticsItem.call(_this);
    ShareRecommendsItem.call(_this);
    ShareExtraData.call(_this);
    ShareUserStatisticsItem.call(_this);
    ShareUserFavoriteItem.call(_this);

  };

  /**
   * Constructs a <code>ShareCard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShareCard} obj Optional instance to populate.
   * @return {module:model/ShareCard} The populated <code>ShareCard</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      QuestionItem.constructFromObject(data, obj);
      BasicShare.constructFromObject(data, obj);
      AuthorItem.constructFromObject(data, obj);
      ShareGroupItem.constructFromObject(data, obj);
      RightToViewShare.constructFromObject(data, obj);
      ShareStatisticsItem.constructFromObject(data, obj);
      ShareRecommendsItem.constructFromObject(data, obj);
      ShareExtraData.constructFromObject(data, obj);
      ShareUserStatisticsItem.constructFromObject(data, obj);
      ShareUserFavoriteItem.constructFromObject(data, obj);
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [TagResponse]);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(QuestionItem.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Array.<module:model/TagResponse>} tags
   */
  exports.prototype['tags'] = undefined;

  // Implement BasicShare interface:
  /**
   * @member {Number} id
   */
exports.prototype['id'] = undefined;

  /**
   * @member {Number} group_id
   */
exports.prototype['group_id'] = undefined;

  /**
   * @member {String} title
   * @default ''
   */
exports.prototype['title'] = '';

  /**
   * @member {String} uid_author
   * @default ''
   */
exports.prototype['uid_author'] = '';

  /**
   * @member {String} reply_reference
   * @default ''
   */
exports.prototype['reply_reference'] = '';

  /**
   * @member {Boolean} is_check
   * @default true
   */
exports.prototype['is_check'] = true;

  /**
   * @member {module:model/BasicShare.ContentTypeEnum} content_type
   */
exports.prototype['content_type'] = undefined;

  /**
   * @member {module:model/BasicShare.ShareTypeEnum} share_type
   */
exports.prototype['share_type'] = undefined;

  /**
   * @member {String} text
   * @default ''
   */
exports.prototype['text'] = '';

  /**
   * @member {Array.<module:model/RichShareContent>} links
   */
exports.prototype['links'] = undefined;

  /**
   * @member {Number} related_id
   */
exports.prototype['related_id'] = undefined;

  /**
   * @member {Number} parent_id
   */
exports.prototype['parent_id'] = undefined;

  /**
   * @member {Boolean} is_recommended
   */
exports.prototype['is_recommended'] = undefined;

  /**
   * @member {Boolean} is_from_leader
   */
exports.prototype['is_from_leader'] = undefined;

  /**
   * @member {Boolean} is_top
   */
exports.prototype['is_top'] = undefined;

  /**
   * @member {Date} created_at
   */
exports.prototype['created_at'] = undefined;

  /**
   * @member {String} question_content
   * @default ''
   */
exports.prototype['question_content'] = '';

  /**
   * @member {Number} words_num
   */
exports.prototype['words_num'] = undefined;

  // Implement AuthorItem interface:
  /**
   * @member {module:model/SimpleUser} author
   */
exports.prototype['author'] = undefined;

  // Implement ShareGroupItem interface:
  /**
   * @member {module:model/PrivilegeGroup} group
   */
exports.prototype['group'] = undefined;

  // Implement RightToViewShare interface:
  /**
   * @member {Boolean} can_see_detail
   * @default false
   */
exports.prototype['can_see_detail'] = false;

  // Implement ShareStatisticsItem interface:
  /**
   * @member {module:model/ShareStatistics} statistics
   */
exports.prototype['statistics'] = undefined;

  // Implement ShareRecommendsItem interface:
  /**
   * @member {Array.<module:model/ReplyResponse>} recommends
   */
exports.prototype['recommends'] = undefined;

  // Implement ShareExtraData interface:
  /**
   * @member {Array.<module:model/AwardResponse>} awards
   */
exports.prototype['awards'] = undefined;

  /**
   * @member {Array.<module:model/AwardResponse>} head_awards
   */
exports.prototype['head_awards'] = undefined;

  /**
   * @member {Array.<module:model/ReplyResponse>} replies
   */
exports.prototype['replies'] = undefined;

  // Implement ShareUserStatisticsItem interface:
  /**
   * @member {module:model/ShareUserStatistics} current_user_statistics
   */
exports.prototype['current_user_statistics'] = undefined;

  // Implement ShareUserFavoriteItem interface:
  /**
   * @member {Boolean} current_user_favorite
   * @default false
   */
exports.prototype['current_user_favorite'] = false;



  return exports;
}));


