/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserAvatar'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserAvatar'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.SimpleUser = factory(root.Mimir.ApiClient, root.Mimir.UserAvatar);
  }
}(this, function(ApiClient, UserAvatar) {
  'use strict';




  /**
   * The SimpleUser model module.
   * @module model/SimpleUser
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SimpleUser</code>.
   * @alias module:model/SimpleUser
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>SimpleUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimpleUser} obj Optional instance to populate.
   * @return {module:model/SimpleUser} The populated <code>SimpleUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uid')) {
        obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
      }
      if (data.hasOwnProperty('nickname')) {
        obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('is_title_authorization')) {
        obj['is_title_authorization'] = ApiClient.convertToType(data['is_title_authorization'], 'Boolean');
      }
      if (data.hasOwnProperty('avatar_key')) {
        obj['avatar_key'] = ApiClient.convertToType(data['avatar_key'], 'String');
      }
      if (data.hasOwnProperty('avatar')) {
        obj['avatar'] = UserAvatar.constructFromObject(data['avatar']);
      }
      if (data.hasOwnProperty('ranking')) {
        obj['ranking'] = ApiClient.convertToType(data['ranking'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} uid
   */
  exports.prototype['uid'] = undefined;
  /**
   * @member {String} nickname
   * @default ''
   */
  exports.prototype['nickname'] = '';
  /**
   * @member {String} title
   * @default ''
   */
  exports.prototype['title'] = '';
  /**
   * @member {Boolean} is_title_authorization
   * @default false
   */
  exports.prototype['is_title_authorization'] = false;
  /**
   * @member {String} avatar_key
   * @default ''
   */
  exports.prototype['avatar_key'] = '';
  /**
   * @member {module:model/UserAvatar} avatar
   */
  exports.prototype['avatar'] = undefined;
  /**
   * @member {module:model/SimpleUser.RankingEnum} ranking
   */
  exports.prototype['ranking'] = undefined;


  /**
   * Allowed values for the <code>ranking</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RankingEnum = {
    /**
     * value: "gold"
     * @const
     */
    "gold": "gold",
    /**
     * value: "silver"
     * @const
     */
    "silver": "silver",
    /**
     * value: "bronze"
     * @const
     */
    "bronze": "bronze",
    /**
     * value: "none"
     * @const
     */
    "none": "none"  };


  return exports;
}));


