/**
 * Mimir
 * APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Mimir) {
      root.Mimir = {};
    }
    root.Mimir.WxConfig = factory(root.Mimir.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WxConfig model module.
   * @module model/WxConfig
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WxConfig</code>.
   * @alias module:model/WxConfig
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>WxConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WxConfig} obj Optional instance to populate.
   * @return {module:model/WxConfig} The populated <code>WxConfig</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('debug')) {
        obj['debug'] = ApiClient.convertToType(data['debug'], 'Boolean');
      }
      if (data.hasOwnProperty('appId')) {
        obj['appId'] = ApiClient.convertToType(data['appId'], 'String');
      }
      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
      }
      if (data.hasOwnProperty('nonceStr')) {
        obj['nonceStr'] = ApiClient.convertToType(data['nonceStr'], 'String');
      }
      if (data.hasOwnProperty('signature')) {
        obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('jsApiList')) {
        obj['jsApiList'] = ApiClient.convertToType(data['jsApiList'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} debug
   * @default false
   */
  exports.prototype['debug'] = false;
  /**
   * @member {String} appId
   */
  exports.prototype['appId'] = undefined;
  /**
   * @member {String} timestamp
   */
  exports.prototype['timestamp'] = undefined;
  /**
   * @member {String} nonceStr
   */
  exports.prototype['nonceStr'] = undefined;
  /**
   * @member {String} signature
   */
  exports.prototype['signature'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {Array.<String>} jsApiList
   */
  exports.prototype['jsApiList'] = undefined;



  return exports;
}));


