'use strict'
const path = require('path')
const Generator = require('yeoman-generator')
const chalk = require('chalk')
const yosay = require('yosay')

const rootPath = path.resolve(__dirname, '../..')

module.exports = class extends Generator {
  constructor(args, options) {
    super(args, options)

    this.log(yosay(
      'Welcome to the excellent ' + chalk.green('generator-large-fe') + ' generator!'
    ))

    this.sourceRoot(rootPath)
  }

  prompting() {
    return this.prompt([
      {
        type    : 'input',
        name    : 'name',
        message : 'Please choose your application name',
        default : this.appname
      },
      {
        type: 'confirm',
        name: 'less',
        message: 'Do you want to use less?',
        default: true
      },
      {
        type: 'confirm',
        name: 'postcss',
        message: 'Enable postcss?',
        default: true
      },
      {
        type: 'list',
        name: 'component',
        message: 'Which component package do you want to use?',
        choices: ['ant-design', 'ant-design-mobile'],
        default: 'ant-design'
      }
    ]).then((answers) => {
      this.name = answers.name
      this.less = answers.less
      this.postcss = answers.postcss
      this.component = answers.component
    })
  }

  configuring() {
    let defaultPackageJSON = this.fs.readJSON(path.resolve(__dirname, './templates/package.json'))
    let packageJSON = {
      name: this.appname,
      private: true,
      version: '0.0.1',
      description: `${this.appname} - Generated by generator-large-fe`,
      scripts: defaultPackageJSON.scripts,
      repository: '',
      keywords: [],
      author: 'Your name here',
      devDependencies: defaultPackageJSON.devDependencies,
      dependencies: defaultPackageJSON.dependencies
    }

    // style 
    if (!this.less) {
      delete packageJSON.devDependencies.less
      delete packageJSON.devDependencies['less-loader']
    }

    if (!this.postcss) {
      delete packageJSON.devDependencies['postcss-import']
      delete packageJSON.devDependencies['postcss-loader']
    }

    // component lib
    if (this.component === 'ant-design') {
      delete packageJSON.devDependencies['ant-design']
    }

    if (this.component === 'ant-design-mobile') {
      delete packageJSON.devDependencies['ant-design-mobile']
    }

  }

  writing() {
    this.fs.copy(
      this.templatePath('generators/app/templates/'),
      this.destinationPath('./')
    )

    this.fs.copy(
      this.templatePath('generators/app/templates/.*'),
      this.destinationPath('./')
    )
  }

  install() {
    // this.installDependencies()
  }
}